"""
Localization helpers for the application UI and translation target language.
"""
from __future__ import annotations

from PyQt5.QtCore import QLocale

SUPPORTED_APP_LANGUAGES = ("ja", "en", "zh", "ko")

LANGUAGE_NAMES = {
    "ja": "日本語",
    "en": "English",
    "zh": "中文",
    "ko": "한국어",
}

STRINGS = {
    "ja": {
        "window_title": "キャプチャAI翻訳くん",
        "status_ready": "準備完了 (ホットキー: Ctrl+Shift+X) / 送信前に内容をご確認ください",
        "status_select_area": "画面の翻訳したい領域をドラッグで選択してください...",
        "status_capture_cancelled": "キャプチャがキャンセルされました",
        "status_processing": "キャプチャ完了、翻訳処理中...",
        "status_translation_done": "翻訳が完了しました。(API: GOOGLE)",
        "status_translation_done_with_model": "翻訳が完了しました。(API: GOOGLE / モデル: {model})",
        "status_settings_saved": "設定を保存しました",
        "status_copy_original": "原文をクリップボードにコピーしました",
        "status_copy_translation": "翻訳をクリップボードにコピーしました",
        "capture_button": "画面範囲をキャプチャ",
        "notice": "【注意】選択した画面領域の画像および抽出テキストは、Google AI へ送信されます。機密情報は含めないでください。",
        "original_label": "原文:",
        "translation_label": "翻訳:",
        "copy_button": "コピー",
        "progress_label": "翻訳処理中...",
        "file_menu": "ファイル",
        "exit_action": "終了",
        "settings_menu": "設定 / Setting",
        "settings_action": "設定 / Setting",
        "help_menu": "ヘルプ",
        "about_action": "バージョン情報",
        "usage_action": "使い方",
        "about_title": "バージョン情報",
        "about_text": "OCR翻訳ツール v0.0.1\n© 2025 tarutaru247",
        "usage_title": "使い方",
        "usage_text": "ホットキー(Ctrl+Shift+X)を押して、\n翻訳したいテキストの範囲を選択します。\n\nメインウィンドウのボタンからも実行できます。\n必要に応じて結果をコピーして利用できます",
        "settings_dialog_title": "設定 / Setting",
        "settings_api_group": "API設定 / API Setting",
        "settings_language_group": "言語 / Language",
        "google_api_key": "Google APIキー:",
        "google_api_key_placeholder": "Google AI Studio の APIキーを入力",
        "llm_setting": "LLM設定:",
        "llm_auto": "自動",
        "llm_custom": "カスタム",
        "auto_model_note": "自動では通常 `gemini-3.1-flash-lite-preview` を使い、混雑や制限時は `gemma-4-26b-a4b-it` に自動切替します。",
        "model_name": "モデル名:",
        "custom_model_placeholder": "例: gemini-2.5-pro, gemma-3-27b-it",
        "custom_model_note": "カスタム選択時のみ、入力したモデル名をそのまま Google API に渡します。",
        "timeout": "APIタイムアウト (秒):",
        "verify_api_key": "APIキーを検証",
        "cancel": "キャンセル",
        "save": "保存",
        "app_language": "言語 / Language:",
        "validation_title": "入力不足",
        "validation_custom_model": "カスタムを使う場合はモデル名を入力してください。",
        "error_title": "エラー",
        "verify_ok_title": "APIキー検証",
        "verify_ok_message": "APIキーは有効です。",
        "verify_ng_message": "APIキーが無効です: {message}",
        "missing_translator": "Google翻訳サービスが見つかりません。",
        "translation_failed": "翻訳に失敗しました。\n詳細: {detail}",
        "generic_error": "不明なエラーが発生しました。",
        "capture_failed": "テキストの抽出に失敗しました。",
    },
    "en": {
        "window_title": "Capture AI Translator",
        "status_ready": "Ready (Hotkey: Ctrl+Shift+X) / Check the content before sending",
        "status_select_area": "Drag to select the area you want to translate...",
        "status_capture_cancelled": "Capture was cancelled",
        "status_processing": "Capture completed. Translating...",
        "status_translation_done": "Translation completed. (API: GOOGLE)",
        "status_translation_done_with_model": "Translation completed. (API: GOOGLE / Model: {model})",
        "status_settings_saved": "Settings saved",
        "status_copy_original": "Original text copied to clipboard",
        "status_copy_translation": "Translation copied to clipboard",
        "capture_button": "Capture Screen Area",
        "notice": "Warning: The selected image area and extracted text will be sent to Google AI. Do not include confidential information.",
        "original_label": "Original:",
        "translation_label": "Translation:",
        "copy_button": "Copy",
        "progress_label": "Translating...",
        "file_menu": "File",
        "exit_action": "Exit",
        "settings_menu": "設定 / Setting",
        "settings_action": "設定 / Setting",
        "help_menu": "Help",
        "about_action": "About",
        "usage_action": "How to Use",
        "about_title": "About",
        "about_text": "OCR Translator v0.0.1\n© 2025 tarutaru247",
        "usage_title": "How to Use",
        "usage_text": "Press the hotkey (Ctrl+Shift+X)\nand select the text area you want to translate.\n\nYou can also start it from the main window button.\nCopy the result if needed.",
        "settings_dialog_title": "設定 / Setting",
        "settings_api_group": "API Setting",
        "settings_language_group": "言語 / Language",
        "google_api_key": "Google API Key:",
        "google_api_key_placeholder": "Enter your Google AI Studio API key",
        "llm_setting": "LLM Setting:",
        "llm_auto": "Auto",
        "llm_custom": "Custom",
        "auto_model_note": "Auto mode normally uses `gemini-3.1-flash-lite-preview` and switches to `gemma-4-26b-a4b-it` when rate-limited or unavailable.",
        "model_name": "Model Name:",
        "custom_model_placeholder": "e.g. gemini-2.5-pro, gemma-3-27b-it",
        "custom_model_note": "Only in custom mode, the entered model name is passed directly to the Google API.",
        "timeout": "API Timeout (sec):",
        "verify_api_key": "Verify API Key",
        "cancel": "Cancel",
        "save": "Save",
        "app_language": "言語 / Language:",
        "validation_title": "Missing Input",
        "validation_custom_model": "Enter a model name when custom mode is selected.",
        "error_title": "Error",
        "verify_ok_title": "API Key Verification",
        "verify_ok_message": "The API key is valid.",
        "verify_ng_message": "The API key is invalid: {message}",
        "missing_translator": "Google translation service was not found.",
        "translation_failed": "Translation failed.\nDetails: {detail}",
        "generic_error": "An unknown error occurred.",
        "capture_failed": "Failed to extract text.",
    },
    "zh": {
        "window_title": "截图 AI 翻译",
        "status_ready": "准备完成（快捷键: Ctrl+Shift+X）/ 发送前请确认内容",
        "status_select_area": "请拖动选择要翻译的区域...",
        "status_capture_cancelled": "已取消截图",
        "status_processing": "截图完成，正在翻译...",
        "status_translation_done": "翻译完成。(API: GOOGLE)",
        "status_translation_done_with_model": "翻译完成。(API: GOOGLE / 模型: {model})",
        "status_settings_saved": "设置已保存",
        "status_copy_original": "原文已复制到剪贴板",
        "status_copy_translation": "翻译结果已复制到剪贴板",
        "capture_button": "截取屏幕区域",
        "notice": "注意：所选区域图像与提取出的文本会发送到 Google AI。请勿包含机密信息。",
        "original_label": "原文：",
        "translation_label": "翻译：",
        "copy_button": "复制",
        "progress_label": "正在翻译...",
        "file_menu": "文件",
        "exit_action": "退出",
        "settings_menu": "設定 / Setting",
        "settings_action": "設定 / Setting",
        "help_menu": "帮助",
        "about_action": "关于",
        "usage_action": "使用方法",
        "about_title": "关于",
        "about_text": "OCR 翻译工具 v0.0.1\n© 2025 tarutaru247",
        "usage_title": "使用方法",
        "usage_text": "按下快捷键（Ctrl+Shift+X），\n选择要翻译的文本区域。\n\n也可以从主窗口按钮启动。\n如有需要可复制结果。",
        "settings_dialog_title": "設定 / Setting",
        "settings_api_group": "API 设置",
        "settings_language_group": "言語 / Language",
        "google_api_key": "Google API 密钥：",
        "google_api_key_placeholder": "请输入 Google AI Studio 的 API 密钥",
        "llm_setting": "LLM 设置：",
        "llm_auto": "自动",
        "llm_custom": "自定义",
        "auto_model_note": "自动模式默认使用 `gemini-3.1-flash-lite-preview`，在限流或不可用时切换到 `gemma-4-26b-a4b-it`。",
        "model_name": "模型名：",
        "custom_model_placeholder": "例如: gemini-2.5-pro, gemma-3-27b-it",
        "custom_model_note": "仅在自定义模式下，输入的模型名会原样传给 Google API。",
        "timeout": "API 超时（秒）：",
        "verify_api_key": "验证 API 密钥",
        "cancel": "取消",
        "save": "保存",
        "app_language": "言語 / Language:",
        "validation_title": "输入不足",
        "validation_custom_model": "使用自定义时请输入模型名。",
        "error_title": "错误",
        "verify_ok_title": "API 密钥验证",
        "verify_ok_message": "API 密钥有效。",
        "verify_ng_message": "API 密钥无效：{message}",
        "missing_translator": "未找到 Google 翻译服务。",
        "translation_failed": "翻译失败。\n详情：{detail}",
        "generic_error": "发生未知错误。",
        "capture_failed": "提取文本失败。",
    },
    "ko": {
        "window_title": "캡처 AI 번역기",
        "status_ready": "준비 완료 (단축키: Ctrl+Shift+X) / 전송 전에 내용을 확인하세요",
        "status_select_area": "번역할 영역을 드래그해서 선택하세요...",
        "status_capture_cancelled": "캡처가 취소되었습니다",
        "status_processing": "캡처 완료, 번역 중...",
        "status_translation_done": "번역이 완료되었습니다. (API: GOOGLE)",
        "status_translation_done_with_model": "번역이 완료되었습니다. (API: GOOGLE / 모델: {model})",
        "status_settings_saved": "설정이 저장되었습니다",
        "status_copy_original": "원문이 클립보드에 복사되었습니다",
        "status_copy_translation": "번역문이 클립보드에 복사되었습니다",
        "capture_button": "화면 영역 캡처",
        "notice": "주의: 선택한 이미지 영역과 추출된 텍스트는 Google AI로 전송됩니다. 기밀 정보는 포함하지 마세요.",
        "original_label": "원문:",
        "translation_label": "번역:",
        "copy_button": "복사",
        "progress_label": "번역 중...",
        "file_menu": "파일",
        "exit_action": "종료",
        "settings_menu": "設定 / Setting",
        "settings_action": "設定 / Setting",
        "help_menu": "도움말",
        "about_action": "정보",
        "usage_action": "사용 방법",
        "about_title": "정보",
        "about_text": "OCR 번역 도구 v0.0.1\n© 2025 tarutaru247",
        "usage_title": "사용 방법",
        "usage_text": "단축키(Ctrl+Shift+X)를 누른 후,\n번역할 텍스트 영역을 선택하세요.\n\n메인 창의 버튼으로도 실행할 수 있습니다.\n필요하면 결과를 복사해서 사용하세요.",
        "settings_dialog_title": "設定 / Setting",
        "settings_api_group": "API 설정",
        "settings_language_group": "言語 / Language",
        "google_api_key": "Google API 키:",
        "google_api_key_placeholder": "Google AI Studio API 키를 입력하세요",
        "llm_setting": "LLM 설정:",
        "llm_auto": "자동",
        "llm_custom": "사용자 지정",
        "auto_model_note": "자동 모드에서는 기본적으로 `gemini-3.1-flash-lite-preview`를 사용하고, 제한이나 장애가 있으면 `gemma-4-26b-a4b-it`로 전환합니다.",
        "model_name": "모델명:",
        "custom_model_placeholder": "예: gemini-2.5-pro, gemma-3-27b-it",
        "custom_model_note": "사용자 지정 모드에서만 입력한 모델명을 그대로 Google API에 전달합니다.",
        "timeout": "API 타임아웃(초):",
        "verify_api_key": "API 키 확인",
        "cancel": "취소",
        "save": "저장",
        "app_language": "言語 / Language:",
        "validation_title": "입력 부족",
        "validation_custom_model": "사용자 지정을 쓰려면 모델명을 입력하세요.",
        "error_title": "오류",
        "verify_ok_title": "API 키 확인",
        "verify_ok_message": "API 키가 유효합니다.",
        "verify_ng_message": "API 키가 올바르지 않습니다: {message}",
        "missing_translator": "Google 번역 서비스를 찾을 수 없습니다.",
        "translation_failed": "번역에 실패했습니다.\n상세: {detail}",
        "generic_error": "알 수 없는 오류가 발생했습니다.",
        "capture_failed": "텍스트 추출에 실패했습니다.",
    },
}


def normalize_app_language(language_code: str | None) -> str:
    """Normalize app language code to a supported value."""
    lowered = (language_code or "").strip().lower()
    if lowered.startswith("zh"):
        return "zh"
    if lowered.startswith("ko"):
        return "ko"
    if lowered.startswith("en"):
        return "en"
    return "ja"


def get_system_default_language() -> str:
    """Return the supported language that best matches the OS UI language."""
    return normalize_app_language(QLocale.system().name())


def get_ui_string(language_code: str, key: str, **kwargs) -> str:
    """Look up a UI string for the specified app language."""
    normalized = normalize_app_language(language_code)
    value = STRINGS.get(normalized, STRINGS["ja"]).get(key, STRINGS["ja"].get(key, key))
    if kwargs:
        return value.format(**kwargs)
    return value


def get_language_name(language_code: str) -> str:
    """Return native language name."""
    normalized = normalize_app_language(language_code)
    return LANGUAGE_NAMES.get(normalized, LANGUAGE_NAMES["ja"])
